apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: j2j3u8a1e-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/j2j3u8a1e-dotnet-basic-gitops